# Generated by Django 5.1.7 on 2025-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
